version: '3'
services:
  process-manager:
    image: "nv4re/melonade-process-manager:v0.0.2"
    ports:
      - "80:80"
    depends_on:
      - "redis"
      - "zookeeper"
      - "kafka"
    environment:
     - melonade.namespace=docker-compose
     - runners.max=2
     - kafka.conf.bootstrap.servers=kafka:9092
     - server.port=80
     - server.enabled=true
     - task-definition.type=ZOOKEEPER
     - task-definition.zookeeper.connections=zookeeper:2181
     - workflow-definition.type=ZOOKEEPER
     - workflow-definition.zookeeper.connections=zookeeper:2181
     - task-instance.type=REDIS
     - task-instance.redis.host=redis
     - workflow-instance.type=REDIS
     - workflow-instance.redis.host=redis
     - transaction-instance.type=REDIS
     - transaction-instance.redis.host=redis

  event-logger:
    image: "nv4re/melonade-event-logger:v0.0.2"
    depends_on:
      - "elasticsearch"
      - "kafka"
    environment:
     - melonade.namespace=docker-compose
     - runners.max=2
     - kafka.conf.bootstrap.servers=kafka:9092
     - event-store.type=ELASTICSEARCH
     - event-store.elasticsearch.host=http://elasticsearch:9200

  time-keeper:
    image: "nv4re/melonade-time-keeper:v0.0.2"
    depends_on:
      - "redis"
      - "zookeeper"
      - "kafka"
    environment:
     - melonade.namespace=docker-compose
     - runners.max=2
     - kafka.conf.bootstrap.servers=kafka:9092
     - timer-instance.type=REDIS
     - transaction-instance.redis.host=redis
     - timer-leader.type=ZOOKEEPER
     - timer-leader.zookeeper.connections=zookeeper:2181

  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'

  elasticsearch:
    image: "elasticsearch:7.4.2"
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node

  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
